<a href="https://colab.research.google.com/github/SatyamSingh-16/AI-Journey/blob/main/Python/Day-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = [10,20,3,33,60]

result = np.array(arr)
print(result *2)
print(result.ndim)
print(result.shape)
print(result.size)

[ 20  40   6  66 120]
1
(5,)
5


In [ ]:
import numpy as np

arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr[1,1])
print(arr[0])
print(arr[0,1],arr[1,1],arr[2,1])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
2
(3, 3)
int64
25
[ 5 10 15]
10 25 40


In [ ]:
import numpy as np
arr = np.zeros((3,2))
print(arr)

arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(2,13)
print(arr2)

arr3 = np.linspace(0,10,5)
print(arr3)

arr4 = np.eye(4)
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11 12]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
arr = np.random.rand(5)
print(arr)

arr1 = np.random.randint(1,100,(3,4))
print(arr1)

[0.08923928 0.90358658 0.08191995 0.73512908 0.76794476]
[[81  1 59 13]
 [43 27  3 70]
 [68 36 81  4]]


In [41]:
import numpy as np
students = np.array([
    [85, 78, 92],
    [67, 88, 76],
    [90, 95, 89],
    [72, 65, 80]
])

print(students.ndim)
print(students.shape)
print(students.size)
print(students.dtype)

print(np.mean(students,axis=0))
print(np.mean(students,axis=1))
print(np.argmax(students))
print(students[students > 85])



2
(4, 3)
12
int64
[78.5  81.5  84.25]
[85.         77.         91.33333333 72.33333333]
7
[92 88 90 95 89]
