<a href="https://colab.research.google.com/github/SatyamSingh-16/AI-Journey/blob/main/Numpy/Day-02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

arr1 = arr.reshape(3,2)
print(arr1)
print(arr1.shape)
print(arr.size)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [19]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[7,8,9],[2,5,7]])
flat = arr.flatten()
print(flat)

print(arr.T)

res = np.concatenate((arr,arr1),axis=1)
print(res)
np.vstack((arr))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 7 8 9]
 [4 5 6 2 5 7]]


array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

res = np.dot(a,b)
print(res)

32


In [27]:
import numpy as np

arr = np.arange(1,13)

print(arr.shape)
res1 = arr.reshape((3,4))
print(res1)
res2 = arr.reshape((4,3))
print(res2)
print(res1.flatten())
print(res1.T)
print(res1[:,1])
print(res1[:2,-2:])





(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 2  6 10]
[[3 4]
 [7 8]]


In [28]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a +b)
print(a *b)
print(a @b)

[11 22 33]
[10 40 90]
140


In [36]:
import numpy as np

X = np.array([
    [20, 30000],
    [25, 40000],
    [30, 60000],
    [35, 80000],
    [40, 100000]
])

print(X.shape)
print(X.ndim)
print(X.size)
age = X[:,0]
print(np.mean(age))
salary = X[:,1]
print(np.mean(salary))

print(np.max(salary))
print(np.argmax(salary))

res = np.where(salary > 50000,"G","S")
print(res)

res1 = age - np.mean(age)
res2 = res1 / np.std(age)
print(res2)

(5, 2)
2
10
30.0
62000.0
100000
4
['S' 'S' 'G' 'G' 'G']
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
